QUESTION 1

Numpy Final Assignment
Solve the below problem by using only Numpy on the tip data set.

What is the total bill value?



In [38]:
import numpy as np

In [39]:
data = np.genfromtxt(r'/content/sample_data/tipsf.csv', delimiter=',', skip_header=1)
data

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

What is the total bill value?

In [40]:
np.sum(data[:,1])

4827.77

What is the total tip value?

In [41]:
np.sum(data[:,2])

731.5799999999999

Count how many Sunday, Saturday, Thursday,friday,are there.

In [42]:
np.unique(data[:,5], return_counts=True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19]))

How many smokers are there?

In [43]:
smokers=data[:,4]
np.sum(smokers)

93.0

What is the average tip given by females and males?

In [44]:
tip = data[:, 2]
sex = data[:, 3]

male = np.mean(tip[sex == 0])
female = np.mean(tip[sex == 1])

print("Average tip given by males:", male)
print("Average tip given by females:", female)

Average tip given by males: 2.8334482758620685
Average tip given by females: 3.0896178343949043


 How many males and females are going for dinner and lunch

In [45]:
time = data[:,6]

male_lunch_count = np.sum((sex == 0) & (time == 1))
male_dinner_count = np.sum((sex == 0) & (time == 0))
female_lunch_count = np.sum((sex == 1) & (time == 1))
female_dinner_count = np.sum((sex == 1) & (time == 0))

print("No of male lunch:", male_lunch_count )
print("No of female lunch:",female_lunch_count)
print("No of male Dinner:", male_dinner_count )
print("No of female Dinner:",female_dinner_count)

No of male lunch: 35
No of female lunch: 33
No of male Dinner: 52
No of female Dinner: 124


What is the min and max tip given?

In [46]:
print("Minimum tip : ",np.min(tip))
print("Maximum tip : ",np.max(tip))

Minimum tip :  1.0
Maximum tip :  10.0


How much amount has been spent by female and male.

In [47]:
total_bill= data[:,1]

male = np.sum(total_bill[sex == 0])
female = np.sum(total_bill[sex == 1])

print('Total bill for male: ', male)
print('Total bill for female:' , female)

Total bill for male:  1570.9499999999996
Total bill for female: 3256.8199999999997


Find out the AVG size.

In [48]:
np.mean(data[:,7])

2.569672131147541

Find out how many male,female smokers are there.

In [49]:
male_smokers= np.sum(smokers[(sex== 0) & (smokers== 1)])
female_smokers= np.sum(smokers[(sex== 1) & (smokers== 1)])

print('male_smokers:',male_smokers)
print('female_smokers:',female_smokers)

male_smokers: 33.0
female_smokers: 60.0


QUESTION 2

In [50]:
data1 = np.genfromtxt('/content/sample_data/train_extended.csv', delimiter=',', skip_header=1)
data1

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

What is the maximum and minimum length?

In [51]:
length= data1[:,1]
minimum_length = np.min(length)
maximum_length = np.max(length)

In [52]:
print('Minimum length: ', minimum_length)
print('Maximum length:', maximum_length)

Minimum length:  0.0
Maximum length: 2.25


Find out the difference between maximum and minimum length

In [53]:
range= maximum_length - minimum_length
print(range)

2.25


Find column-wise average

In [54]:
np.mean(data1, axis=0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

Find out all the age whose height is greater than 0.4.

In [55]:
age=data1[:,7]

height=data1[:,2]

greater_age=age[height>0.4]

print("Ages where height is greater than 0.4:", greater_age)
print('Numbers of ages:', len(greater_age))

Ages where height is greater than 0.4: [11. 14. 13. ... 11. 11. 11.]
Numbers of ages: 55336


What is the average height and weight of the person whose age is 10?

In [56]:
weight=data1[:,3]

average_height = np.mean(height[age == 10])
average_weight = np.mean(weight[age == 10])


print("Average height of people whose age is 10:", average_height)
print("Average weight of people whose age is 10:", average_weight)

Average height of people whose age is 10: 0.3833672856539947
Average weight of people whose age is 10: 28.243308450511314


What is the total shell weight.

In [57]:
np.sum(weight)


4624687.262596481

How many persons belong to each and every unique age.

In [58]:
np.unique(age, return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57]))


What is the difference between shucked weight and visua weight .


In [59]:
shucked_weight = data1[:,4]

viscera_weight = data1[:,5]

difference = shucked_weight - viscera_weight


print("Difference between shucked weight and viscera weight:\n", difference)


Difference between shucked weight and viscera weight:
 [5.9817445 3.855532  4.1106775 ... 2.9199985 5.329706  9.8372765]


What is the average height of the persons whose age is between 14 and 19.

In [60]:
average_height = np.mean(height[(age >= 14) & (age <= 19)])

print("Average height:", average_height)

Average height: 0.41489902051107985


What is the average weight if we include viscous and shell weight?

In [61]:
shell_weight = data1[:, 6]

total_weight = shell_weight + viscera_weight

average_weight = np.mean(total_weight)

print("Average weight (viscera and shell weight):", average_weight)

Average weight (viscera and shell weight): 11.62741010435575


QUESTION 3

 Solve the below problem by using only numpy functions on the below-given dataset.




Calculate the average length of all the seashells (Abalone)?

In [62]:
data2 = np.genfromtxt('/content/sample_data/Abelone - abalone_data.csv', delimiter=',', skip_header=1)
data2


array([[ nan,  91.,  73., ...,  20.,  30.,  15.],
       [ nan,  70.,  53., ...,  10.,  14.,   7.],
       [ nan, 106.,  84., ...,  28.,  42.,   9.],
       ...,
       [ nan, 120.,  95., ...,  58.,  62.,   9.],
       [ nan, 125.,  97., ...,  52.,  59.,  10.],
       [ nan, 142., 111., ...,  75.,  99.,  12.]])

Calculate the average length of all the seashells (Abalone)?

In [63]:
lengths= data2[:,1]

average_length = np.mean(lengths)

print("The average length is:", average_length)

The average length is: 104.79841991860187


Calculate the minimum and maximum age in the available data?

In [64]:
ages = data2[:,8]

min_age = np.min(ages)
max_age = np.max(ages)

print("The minimum age is:",min_age)
print("The maximum age is: ",max_age)


The minimum age is: 1.0
The maximum age is:  29.0


Calculate the mean of meat-weight, gut weight, and dried-shell-weight combined?

In [65]:
meat_weight = data2[:,5]

gut_weight = data2[:,6]

dried_shell_weight = data2[:,7]


total_weights = meat_weight + gut_weight + dried_shell_weight


mean = np.mean(total_weights)

print("The mean is:", mean)

The mean is: 155.87072061288006


For all Abalones with age between [10 and 16) calculate the average of whole weight

In [66]:
whole_weight = data2[:,4]

weights = whole_weight[ (ages >= 10) & (ages < 16)]

average_weight = np.mean(weights)

print("The average whole weight is: ", average_weight)


The average whole weight is:  214.54725274725274


Create and add a new column that contains the ratio of the "dried-shell-weight" to that of "whole-weight" (dried-shell-weight / whole-weight)?

In [67]:
ratio= dried_shell_weight / whole_weight

ratio= ratio.reshape(-1, 1)

result = np.concatenate((data2, ratio), axis=1)
print(result)


[[         nan  91.          73.         ...  30.          15.
    0.29126214]
 [         nan  70.          53.         ...  14.           7.
    0.31111111]
 [         nan 106.          84.         ...  42.           9.
    0.31111111]
 ...
 [         nan 120.          95.         ...  62.           9.
    0.26382979]
 [         nan 125.          97.         ...  59.          10.
    0.26940639]
 [         nan 142.         111.         ...  99.          12.
    0.25384615]]


<ipython-input-67-f893bf7c7ae2>:1: RuntimeWarning: invalid value encountered in divide
  ratio= dried_shell_weight / whole_weight


Which Abelone Age has the highest average diameter?

In [68]:
diameters= data2[:,2]

unique_ages = np.unique(ages)

avg_diameter = []
for age in unique_ages:
    avg_diameter.append(np.mean(diameters[ages == age]))


max_avg_diameter = np.max(avg_diameter)
max_age= unique_ages[np.argmax(avg_diameter)]

print("The age with the highest average diameter is: {}, with an average diameter of {}".format(max_age,max_avg_diameter))


The age with the highest average diameter is: 29.0, with an average diameter of 117.0
